services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_DSN: ${DB_DSN}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXP_MINUTES: ${JWT_EXP_MINUTES:-10000}

      # --- app.prod.conf -> [smtp] ---
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      # --- app.prod.conf -> [admin] ---
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      APP_ENV: prod

    volumes:
      - uploads:/app/uploads
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  uploads:
